### ISSUE TITLE
Community Hubs

### ISSUE THREAD

**Issue by joatu** [shawnlauzon/joatu#1]
Community Hubs (visible on all maps all the time w/a different symbol)

- Show that the user (given their location) is connected to the closest hub
- Automatically attach projects to their closest hub
- Have all of the community hubs where we have gotten letters of intent (e.g. concordia, cafe osmo, temps libre mile end, mcgill WWF club?*)

**Comment by shawnlauzon** [comment]
@joatu What does it mean to "connect" to a hub? I imagined that there was a different screen for each hub which lists all of the projects, requests, and offers for that hub. Does "connecting" mean that the default screen for the user would be that hub? Or something else?

**Comment by joatu** [comment]
Connecting has more to do with:

- Everyone having a home hub where their vote is calculated towards the valuation of community offers
- Showing everyone who is sharing this hub with you.

It isn't crucial for presentation to have the connection aspect for the presentation (although, I do like the way it appears in Thomas' version of JoatU), but to be able to show the community hub page as you describe it would be nice, even as an incredible basic version.

Having all the projects+requests+offers ordered by distance from the user (who puts their own postal code / coordinates in) would be the most practical in my mind, but I do appreciate the idea of it being separated by hub on the hub page itself.

Having a feed of projects/offers/requests makes the most sense as the default screen in my opinion.

**Comment by shawnlauzon** [comment]
Ok, I understand now. You have a hub you're connected to (which we'll call the home hub) which is relatively permanent. Each item is associated with a hub. You can view the items within the hub, as well as items which are visible independent of their hub, wherever the user is closest to.

The concept of hubs and membership to a hub (especially for voting) makes me think of how one changes home hubs. Once you are a member of a hub (and have voting rights), is it possible to change your hub? Is some sort of process necessary? If you change hubs, do your votes on the previous hub then disappear?

**Comment by joatu** [comment]
> Each item is associated with a hub.

Projects yes. Offers/Requests are associated with a hub because they are associated with a person who has a hub. This second aspect is less  relevant, because a person could theoretically have a work and home hub.

>You can view the items within the hub, as well as items which are visible independent of their hub, wherever the user is closest to.

Yes

> Once you are a member of a hub (and have voting rights), is it possible to change your hub?

Yes

>Is some sort of process necessary?

I don't see why that would be necessary.

>If you change hubs, do your votes on the previous hub then disappear?

The votes that you included for your average valuation will be removed at the end of X period and allocated to your new hub area at the beginning of Y period. I imagine automatic vote readjustments every Z months (but I'm open to other suggestions).

**Comment by shawnlauzon** [comment]
> Projects yes. Offers/Requests are associated with a hub because they are associated with a person who has a hub. This second aspect is less relevant, because a person could theoretically have a work and home hub.

So your offers and requests travel with you when you change hubs. I can see how that makes sense. I'm still going to associate the items with the hub directly (and not through the user). If a user changes hub, we might give the option to change the hub of his or her items. But I think changing hubs can be left as a future exercise.

**Comment by joatu** [comment]
Definitely a future exercise. One thing to consider (again for the future, I'm not sure how you take notes about these kinds of things) is that different offers would have different proximities. For example, if I have a photo studio, I'm not willing to travel at all, it's a fixed point. If I'm a photographer with gear, I'll travel 0.5KM. If I'm teaching piano, maybe I'll travel 10km.

Each person should be able to change their personal settings for themselves (how far they're willing to travel) and how far the offer extends. Let's say I'm scrolling through the list of offers on the list, when I click on one, I can see two circles, my circle around me (how far I'm willing to travel) and the circle around the offer (how far the person offering is willing to travel). We can then decide together visually about a meeting spot.

**Comment by shawnlauzon** [comment]
Yeah, that's even more of a future exercise :) What you're talking about is search and discovery criteria. I think it would be good to create another issue with some thoughts because that is an idea independent of community hubs.

**Comment by shawnlauzon** [comment]
@joatu If you have a list of the hubs, send them to me and I can add them.

**Comment by joatu** [comment]
Cafe Osmo, Mile End Temps Libre, McGill, Concordia, Coop Le Milieu would be a good list to start with.
