### ISSUE TITLE
New users auto-assigned to closest hub

### ISSUE THREAD

**Issue by shawnlauzon** [shawnlauzon/joatu#10]

**Comment by shawnlauzon** [comment]
> @joatu: What happens if a user attempts to sign up but there is no hub in their vicinity?
Good question. What should happen? And what does it mean by "their vicinity"?

My initial idea was just to choose whatever is the closest, even if it's miles away. Happy to discuss a different algorithm.

**Comment by joatu** [comment]
As discussed in #35 , only users that are X distance away should be included in a hub.

**Comment by shawnlauzon** [comment]
Such users are then hubless? And does that mean they have zero privileges in any hub, or 100% privileges in all hubs?

**Comment by joatu** [comment]
For MVP purposes, they have the capability of creating everything, but the disability of seeing nothing. They exist only in stasis, waiting for the appropriate number of users to join. I have an image I drew up a long while ago as a front page (not logged in) showcasing the number of users required to join in different cities before JoatU launched in those spaces. I'm imagining it something like that.

In this way, once it launches in their location, they get a notification and have dozens of offers/requests already prepared to be traded.

**Comment by shawnlauzon** [comment]
I really like this, but it's a separate chunk of work. I created #42 for it. Until then, we will just tell the user that JoatU is not available yet in your area, but will be notified when it is. How does that sound?

I also created #43 for suggesting a new hub when one is opened closer to the person's existing hub.

**Comment by joatu** [comment]
To have them leave their email & postal code (like we have them do currently with mailchimp) makes sense. You can literally direct them to that page. http://alpha.joatu.org/en/alpha_signup
