### ISSUE TITLE
Offers & requests contains description

### ISSUE THREAD

**Issue by shawnlauzon** [shawnlauzon/joatu#24]
Only contains description for now

**Comment by joatu** [comment]
I imagine location could be check-boxes, Home, Community Center, Online Offer.

**Comment by shawnlauzon** [comment]
Could we defer online offers until later? It feels like a different thing and would rather focus on in-person meetings to start.

**Comment by joatu** [comment]
If you believe it would unfocus from the hyperlocality, then alright.

**Comment by shawnlauzon** [comment]
I think it might, at least to start. I certainly think there's a place for it in the future however.

**Comment by joatu** [comment]
Yup, should it be an issue for a future feature?

**Comment by shawnlauzon** [comment]
Created #44
