### ISSUE TITLE
Add more labels to Issues

### ISSUE THREAD

**Issue by joatu** [shawnlauzon/joatu#3]
Bugs, Features, Urgent, Discussion, Future, etc.

Here's the other list we had before for labels : https://github.com/joatuapp/joatu-v2/issues

**Comment by shawnlauzon** [comment]
I don't like having a bunch of labels. I really don't think it's needed for the number of people working on this. The [default labels](https://help.github.com/articles/about-labels/) are good enough for now.

I did just invite you to be a collaborator, however.

**Comment by joatu** [comment]
Sounds good. At the end of the day they're more for you than me.
