### ISSUE TITLE
Anyone can post questions & comments to project 

### ISSUE THREAD

**Issue by shawnlauzon** [shawnlauzon/joatu#38]
These are automatically displayed to everyone. Should this be limited to hub members or anyone?

This is different from #9 in that a separate "logistics" channel is available to accepted project volunteers.

**Comment by shawnlauzon** [comment]
Since only hub members can volunteer for a project, it makes sense that only hub members can post questions and comments.

**Comment by joatu** [comment]
Absolutely.
