### ISSUE TITLE
Profiles contain requests and offers which they created

### ISSUE THREAD

**Issue by shawnlauzon** [shawnlauzon/joatu#46]
Each user thus needs to contain both requests and offers

**Comment by joatu** [comment]
- [ Projects they created] 
- [ Projects they plan on attending] 
- [ Projects they already attended]

**Comment by shawnlauzon** [comment]
Actually I just added the support for the top two, but haven't added the view of the 2nd into the profile; will do that now.

Attendance will wait until the functionality to mark users as attended.
