### ISSUE TITLE
Project volunteers invited to private discussion

### ISSUE THREAD

**Issue by shawnlauzon** [shawnlauzon/joatu#9]
When volunteers are approved by the project organizer, they get access to a separate channel to discuss logistics.

**Comment by joatu** [comment]
Do you become a project volunteer simply by clicking 'i'm in'? Can you comment on the project with questions if you are not a volunteer? For example, you want to know more about the project and have questions.

**Comment by shawnlauzon** [comment]
No, Issue #25 is for accepting volunteers, so just clicking the button puts them in "pending" state.

It's a good point about commenting and asking questions. I can see the need for two sets of conversations: public (questions and answers) and private (logistics). Actually I like that, when you are approved to a project you get access to the logistical channel. WDYT?

**Comment by joatu** [comment]
That makes a lot more sense.

**Comment by shawnlauzon** [comment]
Cool, I created #38 for that, and changing this to be specifically for logistical convo.

**Comment by shawnlauzon** [comment]
Note to self: will implement this as another Conversation, which means we need the regular Project conversation, and then another Logistics conversation, 1:1 with a Project.
